### ISSUE TITLE
Code for Other Experiments

### ISSUE THREAD

**Issue by luyuzhe111** [yaodongyu/ProjNorm#2]
Hi Yaodong,

We are interested in extending your work and wondering you could share the code for other baseline experiments and for other datasets you reported in the paper. Thanks!

Best,
Bryan

**Comment by yaodongyu** [comment]
Hey Bryan, 

Thank you for your interest in our work! Regarding the baselines, we have provided implementation details in Appendix A.1, here are some github repos for implementing some of those:

- ATC: https://github.com/saurabhgarg1996/ATC_code

- Rotation: https://github.com/Simon4Yan/Accuracy-estimation-with-self-supervision

The current repo could be applied to other datasets by using the ProjNorm class in https://github.com/yaodongyu/ProjNorm/blob/c6da47f2a739ca05881c366e4934c080751291c8/projnorm.py#L24.

Please let me know if you have any further questions!

Best,
Yaodong
